### ISSUE TITLE
NBT To-Do performance/usability improvements

### ISSUE THREAD

**Issue by LethalEthan** [LethalEthan/HoneyBEE#13]
- [ ] Store the next `TCompound`'s within the previous compound tag to better traverse in a `[]*TCompund` slice. `TCompound` will likely still exist in its value array as it tells the encoder the order of the objects which is very important.
- [x] Create `AddToList` function, users can just manually add tags to the `[]interface{}` value but will be useful to have functions for it anyway.
- [ ] Create search feature so users can backtrack to tags and change them in writer
- [ ] Create ReaderAndWriter pair?
- [ ] Use generics when they come out, it will make the code a lot cleaner and readable
- [ ] Add support for SNBT
